name: CI

on:
  push:
    branches: 
      - '**'
jobs:
  test:
    name: test CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'pnpm'

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install PNPM
      - run: pnpm install

      - name: Lint
      - run: pnpm lint

      - name: Test
      - run: pnpm test

      - name: Build
      - run: pnpm build
      
